---
- name: Check if Docker is running on all workers
  hosts: workers
  gather_facts: false
  tasks:
    - name: Run docker info
      raw: docker info
      register: docker_info
      changed_when: false

    - name: Show Docker status
      debug:
        msg: "Docker is running fine!"
      when: docker_info.rc == 0
