---
- name: Check Swarm status on manager
  hosts: manager
  gather_facts: false
  tasks:
    - name: Check if node is active in Swarm
      raw: docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'
      register: swarm_status
      changed_when: false

    - name: Fail if Swarm is not active
      fail:
        msg: "Docker Swarm is NOT active!"
      when: swarm_status.stdout | trim != "active"
