---
- name: Deploy Hello World Image to Swarm
  hosts: manager
  gather_facts: false
  tasks:
    - name: Create or Update Swarm Service
      raw: >
        docker service create 
        --name hello-world-app 
        --publish published=8080,target=80 
        --replicas 2
        {{ target_image }} 
        || 
        docker service update 
        --image {{ target_image }} 
        hello-world-app
