---
- name: Deploy Hello World Image to Swarm
  hosts: manager
  gather_facts: false
  tasks:
    - name: Create Swarm Service
      raw: >
        docker service create 
        --name hello-world-app 
        --publish published=8080,target=80 
        --replicas 2
        {{ target_image }}
      register: deploy_result
      ignore_errors: yes

    - name: Update Swarm Service (if already exists)
      raw: >
        docker service update 
        --image {{ target_image }} 
        hello-world-app
      when: deploy_result.rc != 0
