---
- name: Deploy Hello World Image to Swarm
  hosts: manager
  gather_facts: false
  tasks:
    - name: Create Swarm Service
      raw: >
        docker service create 
        --name hello-world-app 
        --publish published=8080,target=80 
        --replicas 2
        {% raw %}{{ target_image }}{% endraw %}
      register: deploy_result
      ignore_errors: yes

    - name: Update Swarm Service
      raw: >
        docker service update 
        --image {% raw %}{{ target_image }}{% endraw %} 
        hello-world-app
      when: deploy_result.rc != 0
